languageCode: "de-DE"
baseUrl: "https://kempen.xyz"
title: "kempen.xyz"
theme: "anubis"
paginate: 10
enableRobotsTXT: false
staticDir: static

author:
  name: "Nils Kempen"

menu:
  main:
  - identifier: posts
    name: Posts
    title: Posts
    url: /posts/
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 0
  - identifier: replies
    name: Replies
    title: Replies
    url: /tags/reply
    weight: 2


params:
  env: production
  author: "Nils Kempen"
  email: kontakt@kempen.xyz # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: "Student, terminal enthusiast"
  images:
    - images/og-featured.png # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark
  readMore: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://jn2p.de/webmentions/receive
    widget: https://jn2p.de/webmentions/ui/dist/widget.js


markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
